FROM node:18.20.2-slim
ENV TZ="Asia/Bangkok"
WORKDIR /app
COPY ./pro-my-express-cadt/package.json ./pro-my-express-cadt/package-lock.json ./
RUN npm install
COPY ./pro-my-express-cadt ./
EXPOSE 4001
CMD ["npm", "run", "dev"]