services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile
    # networks:
    #   - production-networks
# networks:
#   production-networks:
#     name: Nginx
#     external: true